# Generated by Django 5.0.6 on 2024-05-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_email_user_password_alter_bookmark_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_published',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$FSAOn8AnFPGXqWy83MfIP5$jTKHVkt/Dwr6ekzi0T+rWyqPAUY5kBhCkmiHVgsvaD4=', max_length=128),
        ),
    ]
