# Generated by Django 5.0.6 on 2024-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_bookmark_date_published_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="firstName", new_name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$dtQ1MdBQ5iNTgoGykVu172$Lh068lROyG2FThOMDQM4+KtnwLswl9NVRpqxjPmmpwQ=",
                max_length=128,
            ),
        ),
    ]
