# Generated by Django 5.0.6 on 2024-06-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_firstname_user_username_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$gyvylZMhGdxnjX8XoTrICY$TBOkOhg3F2bIGuvoD+szBbsMjASvUxI8D0/zc09Fpl4=",
                max_length=128,
            ),
        ),
    ]
