# Generated by Django 5.0.6 on 2024-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_bookmark_country_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$SGftNsqt3JNgAY7K8XmoQe$g4ZRmFH/3KVBQJ4i6Br4GtjSVeE6GMOHOTEppUnhQ8M=",
                max_length=128,
            ),
        ),
    ]
