# Generated by Django 5.0.6 on 2024-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_bookmark_country_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$iKR9G7J2yivU6Hx64NgqKr$osa+pdS27ooKJ1k/jGePDU5mYzNVSFw9fPorkDVwtfk=",
                max_length=128,
            ),
        ),
    ]
